# Generated by Django 4.2 on 2025-03-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='feedbacks',
        ),
    ]
