# Generated by Django 4.2 on 2025-03-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_rename_comment_feedback_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='storeapp.feedback'),
        ),
    ]
